[package]
name = "oxicord"
version = "0.1.5"
edition = "2024"
authors = ["linuxmobile"]
description = "A lightweight, secure Discord terminal client"
license = "MIT"
repository = "https://github.com/linuxmobile/oxicord"
keywords = ["discord", "tui", "terminal", "client"]
categories = ["command-line-utilities"]

[dependencies]
tokio = { version = "1.49", features = ["full"] }

ratatui = { version = "0.30", features = ["crossterm_0_28"] }
crossterm = { version = "0.28", features = ["event-stream"] }
tui-tree-widget = "0.24"
tui-scrollview = "0.6.2"
tui-textarea = "0.7"
tempfile = "3"

reqwest = { version = "0.12", features = ["json", "rustls-tls"], default-features = false }
tokio-tungstenite = { version = "0.27", features = ["rustls-tls-native-roots"] }
futures-util = "0.3"
chrono = { version = "0.4", features = ["serde"] }
flate2 = "1.1"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

thiserror = "2.0"
color-eyre = "0.6"

toml = "0.8"
directories = "6.0"

keyring = "3"

tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

async-trait = "0.1"

dotenvy = "0.15"

clap = { version = "4.5", features = ["derive", "env"] }
syntect = "5.3.0"

[dev-dependencies]
tokio-test = "0.4"
mockall = "0.14"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
strip = true
